# Default ZSH installation configuraiton
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

zstyle ':omz:update' mode auto
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Custom configuration
alias l='exa -l --header --no-time --group-directories-first'
alias ll='exa -la --header --no-time --group-directories-first'
alias lll='exa -la --header --group-directories-first'
alias cat='bat'
