# Default ZSH installation configuraiton
eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/fayez-theme.omp.json)"

# Custom configuration
alias l='exa -l --header --no-time --group-directories-first'
alias ll='exa -la --header --no-time --group-directories-first'
alias lll='exa -la --header --group-directories-first'
alias cat='bat'
