export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"


zstyle ':omz:update' mode disabled  # disable automatic updates

plugins=(git)

source $ZSH/oh-my-zsh.sh

# Custom configuration
alias l='eza -l --header --no-time --group-directories-first'
alias ll='eza -la --header --no-time --group-directories-first'
alias lll='eza -la --header --group-directories-first'
alias cat='bat'
alias python='python3'
